AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ViewCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: view-count
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: my_lambda_function/
      Handler: app.handler
      Runtime: python3.8
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref ViewCountTable

      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /myapi
            Method: GET
