name: CI/CD backend
run-name: ${{ github.actor }} is running test script
on: [push]
jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pytest
          pip install boto3

      - name: Run Python Tests
        run: python tests/test_lambda_function.py
